buildingManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('dashboard_app.urls')),
    path('', include('general_app.urls')),
    path('account', include('account_app.urls.register_urls')),
    path('account', include('account_app.urls.login_urls')),

    path('manager-panel', include('building_app.urls')),
    path('manager-panel', include('vip_service_app.urls')),
    path('manager-panel', include('charge_app.urls.manager_urls')),
    path('manager-panel', include('notification_app.urls.manager_urls')),
    path('manager-panel', include('payment_request_app.urls')),
    path('manager-panel', include('poll_app.urls.manager_urls')),

    path('resident-panel', include('notification_app.urls.resident_urls')),
    path('resident-panel', include('charge_app.urls.resident_urls')),
    path('resident-panel', include('poll_app.urls.resident_urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

charge_app/urls.py
from django.urls import path

from .views import (ChargeList,
                    CreateCharge,
                    ChargeStatus,
                    UpdateCharge,
                    )

app_name = 'charge_app'

urlpatterns = [
    path('/charge-list', ChargeList.as_view(), name='charge_list'),
    path('/create-charge', CreateCharge.as_view(), name='create_charge'),
    path('/charge-status/<pk>', ChargeStatus.as_view(), name='charge_status'),
    path('/update-charge/<pk>', UpdateCharge.as_view(), name='update_charge'),
]

dashboard_app/urls.py
from django.urls import path

from .views import ManagerDashboard,ResidentDashboard

app_name = 'dashboard_app'

urlpatterns = [
    path('manager-panel/dashboard', ManagerDashboard.as_view(), name='manager_dashboard'),
    path('resident-panel/dashboard', ResidentDashboard.as_view(), name='resident_dashboard'),
]

vip_service_app/urls.py
from django.urls import path

from .views import (
    VipServiceList,
    VipServiceDetail,
    payment_vip_service,
    payment_vip_service_verify
)

app_name = 'vip_service_app'

urlpatterns = [
    path('/pricing', VipServiceList.as_view(), name='vip_service_list'),
    path('/pricing/<slug>', VipServiceDetail.as_view(), name='vip_service_detail'),
    path('/payment-vip-service/<slug:slug>', payment_vip_service, name='payment_vip_service'),
    path('/payment-vip-service-verify/<slug:slug>', payment_vip_service_verify, name='payment_vip_service_verify'),
]

charge_app/views/resident_views.py
from django.http import Http404
from django.utils import timezone
from django.views.generic import ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from buildingManagement.mixins import AccessOwnerChargeStatusMixin, ResidentRequiredMixin
from charge_app.models import ServiceChargeStatus
from building_app.models import Building


class ChargeList(LoginRequiredMixin, ResidentRequiredMixin, ListView):
    model = ServiceChargeStatus
    template_name = 'resident/charge-list.html'

    def get_queryset(self):
        unit = self.request.user.unit
        qs = ServiceChargeStatus.objects.filter(unit=unit)
        return qs


class ChargeDetail(LoginRequiredMixin, ResidentRequiredMixin, AccessOwnerChargeStatusMixin, View):
    template_name = 'resident/charge-detail.html'

    def get(self, request, *args, **kwargs):
        context = {}
        service_charge_status = get_object_or_404(ServiceChargeStatus, pk=kwargs['pk'])

        n = str(request.user.unit.building.card_number)
        context['card_number'] = f'{n[0:4]}-{n[4:8]}-{n[8:12]}-{n[12:16]}'
        context['object'] = service_charge_status
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = {}
        receipt = request.FILES.get('receipt')
        service_charge_status = get_object_or_404(ServiceChargeStatus, pk=kwargs['pk'])

        service_charge_status.receipt = receipt
        service_charge_status.status = 'unpaid_waiting'
        service_charge_status.pay_time = timezone.now()
        service_charge_status.save()

        context['object'] = service_charge_status
        return render(request, self.template_name, context)


@login_required
def payment_charge(request, *args, **kwargs):  # send message function in zarinpal
    if request.user.is_manager:
        raise Http404('شما به این صفحه دسترسی ندارید!')
    unit = request.user.unit
    charge_status_pk = kwargs.get('charge_status_pk')
    service_charge_status = get_object_or_404(ServiceChargeStatus, id=charge_status_pk)
    amount = int(service_charge_status.amount)

    if service_charge_status.unit == unit and service_charge_status.is_paid() == False:
        # redirect to zarinpal - video 57 toplearn in local
        # CallBackUrl = f'{payment-charge-verify}/{charge_status_pk}'
        return redirect('/resident-panel/payment-charge-verify/' + str(charge_status_pk))

    raise Http404()


@login_required
def payment_charge_verify(request, *args, **kwargs):
    if request.user.is_manager:
        raise Http404('شما به این صفحه دسترسی ندارید!')
    # if result.status == 100:
    charge_status_pk = kwargs.get('charge_status_pk')
    service_charge_status = get_object_or_404(ServiceChargeStatus, id=charge_status_pk)
    amount = int(service_charge_status.amount)

    # change status payment in ServiceChargeStatus model
    service_charge_status.status = 'online_paid'
    service_charge_status.pay_time = timezone.now()
    service_charge_status.save()

    # change credit building
    building = request.user.unit.building
    building = get_object_or_404(Building, id=building.id)
    building.credit += amount
    building.save()

    context = {'status': 100}
    return render(request, 'resident/payment-verify.html', context)

notification_app/views/resident_views.py
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, FormView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin

from buildingManagement.mixins import AccessOwnerNotificationMixin, SaveVisitMixin, ResidentRequiredMixin
from notification_app.models import Notification, Comment


class NotificationList(LoginRequiredMixin, ResidentRequiredMixin, ListView):
    model = Notification
    template_name = 'resident/notification-list.html'
    paginate_by = 10

    def get_queryset(self):
        building = self.request.user.unit.building
        qs = super().get_queryset().filter(building=building).order_by('-created')
        return qs


class NotificationDetail(LoginRequiredMixin, ResidentRequiredMixin, AccessOwnerNotificationMixin, SaveVisitMixin,
                         DetailView):
    model = Notification
    template_name = 'resident/notification-detail.html'

    def get_context_data(self, **kwargs):
        context = super(NotificationDetail, self).get_context_data()
        context['comments'] = self.object.comment_set.all().order_by('-created')
        return context


class NotificationFilter(LoginRequiredMixin, ResidentRequiredMixin, ListView):
    model = Notification
    template_name = 'resident/notification-list.html'
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        building = self.request.user.unit.building
        unit = self.request.user.unit

        filter = self.kwargs['filter']

        if filter == 'seen':
            qs = Notification.objects.filter(Q(building_id=building), Q(hits=unit)).order_by(
                '-created')  # notification seen by unit
        elif filter == 'unseen':
            qs = Notification.objects.filter(Q(building_id=building), ~Q(hits=unit)).order_by(
                '-created')  # notification unseen by unit
        else:
            qs = Notification.objects.filter(building_id=building).order_by('-created')  # all notification

        return qs


def notification_comment(request):
    if request.POST:
        comment = request.POST.get('comment')
        notifi_id = request.POST.get('notifi_id')
        unit = request.user.unit
        Comment.objects.create(notification_id=notifi_id, unit=unit, text=comment).save()
    return HttpResponse()

poll_app/views/resident_views.py
from django.http import Http404
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from buildingManagement.mixins import ResidentRequiredMixin

from poll_app.models import Poll, PollOption


class PollList(LoginRequiredMixin, ResidentRequiredMixin, ListView):
    model = Poll
    template_name = 'poll_list_resident.html'

    def get_queryset(self):
        building = self.request.user.unit.building
        return self.model.objects.filter(building=building)


class Vote(LoginRequiredMixin, ResidentRequiredMixin, DetailView):
    model = Poll
    template_name = 'vote.html'

    def get(self, request, **kwargs):
        if request.method == 'GET':
            self.object = super(Vote, self).get_object()
            context = super(DetailView, self).get_context_data(**kwargs)

            unit = request.user.unit
            if unit in self.object.get_votes():
                pre_selected = PollOption.objects.filter(poll=self.object, units=unit).first()
                context['pre_selected'] = pre_selected

            return self.render_to_response(context=context)

    def post(self, request, **kwargs):
        if request.method == 'POST':
            self.object = super(Vote, self).get_object()
            context = super(DetailView, self).get_context_data(**kwargs)

            selected_option = request.POST.get('option')
            if selected_option is None:
                raise Http404()
            option = PollOption.objects.filter(poll=self.object, option=selected_option).first()
            unit = request.user.unit

            participated_polls = Poll.objects.filter(polloption__units=unit)

            if participated_polls:
                context['message'] = 'شما از قبل در این نظر سنجی شرکت کرده اید!'
                return self.render_to_response(context=context)
            else:
                option.units.add(unit)
                context['message'] = 'ثبت شد!'
                return self.render_to_response(context=context)

templates/base_panel/resident/base-resident.html
{% extends 'base_panel/base.html' %}

{% block navbar %}
    {% include 'base_panel/resident/navbar.html' %}
{% endblock %}

{% block sidebar %}
    {% include 'base_panel/resident/sidebar.html' %}
{% endblock %}

{% block content %}{% endblock %}

{% block js_file %}{% endblock %}

templates/base_panel/resident/navbar.html
{% load static %}
{% load humanize %}

<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            {% if request.user.unit.building.is_vip %}
                <a class="nav-link">تا {{ request.user.unit.building.until_vip_time }} روز دیگر ویژه هستید</a>
            {% else %}
                <a href="{% url 'vip_service_app:vip_service_list' %}" class="nav-link">عضو ویژه نیستید</a>
            {% endif %}
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'account_app_login:logout' %}" class="nav-link">خروج</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="جستجو" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav mr-auto-navbav">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{% static "adminLTE/dist/img/user1-128x128.jpg" %}" alt="profile" class="img-size-50 mr-3
                        img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{% static "adminLTE/dist/img/user8-128x128.jpg" %}" alt="UserAvatar"
                             class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{% static "adminLTE/dist/img/user3-128x128.jpg" %}" alt="User Avatar"
                             class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

templates/base_panel/resident/sidebar.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url "dashboard_app:resident_dashboard" %}" class="brand-link">
        <img src='{% static "adminLTE/dist/img/AdminLTELogo.png" %}' alt="logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">پنل مدیریت</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">

            {% if request.user.unit.building.image %}
                <div class="image">
                    <img src="{{ request.user.unit.building.image.url }}" class="img-circle-2" alt="User Image">
                </div>
            {% endif %}

            <div class="info">
                <a href="{% url "dashboard_app:resident_dashboard" %}" id="unit-name" class="d-block">{{ request.user.unit.name }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-item">
                    <a href="{% url 'notification_app_resident:notification_list' %}"
                       class="nav-link {% if '/resident-panel/notification-list' in request.path %}active{% endif %}">
                        <i class="fas fa-th nav-icon"></i>
                        <p>لیست اعلانات</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'charge_app_resident:charge_list' %}"
                       class="nav-link {% if '/resident-panel/charge-list' in request.path %}active{% endif %}">
                        <i class="fas fa-th nav-icon"></i>
                        <p>لیست شارژ ها</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'poll_resident:poll_list' %}"
                       class="nav-link {% if '/resident-panel/poll-list' in request.path %}active{% endif %}">
                        <i class="fas fa-th nav-icon"></i>
                        <p>لیست نظرسنجی ها</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>